@startuml
class dhbw.ipoat.animals.GrownAnimals {
# int cost
# boolean home
# boolean delivering
# int breedingCooldown
# TransportDevice transport
+ TransportDevice getTransport()
}
class dhbw.ipoat.computer.Computer {
- float writingSpeed
- float generationSpeed
- List<Medium> mediaInPC
- String nameOfPc
- float puffer
- float maxPuffer
- float cost
- float dataTransmitted
~ Instant pcStartTime
+ void GenerateData()
+ Instant getPcStartTime()
+ float getPuffer()
+ void transferData(Medium)
+ String getNameOfPc()
}
class dhbw.ipoat.animals.birds.Pigeon {
}
class dhbw.ipoat.medium.Medium {
# String nameOfMedium
# float weight
# float cost
# float data
# String id
# boolean full
+ String getNameOfMedium()
+ boolean isFull()
+ void setFull(boolean)
+ float getData()
+ float getCost()
+ String getId()
+ float getWeight()
+ void setWeight(float)
}
enum dhbw.ipoat.employee.EmployeeNames {
+  Janick
+  Timo
+  Andreas
+  Lars
+  Nico
+  Felix
+  David
+  Markus
+  Christin
+  Claudia
+  Laura
+  Katja
+  Sven
+  Lea
+  Nina
}
class dhbw.ipoat.animals.mammals.Ox {
}
class dhbw.ipoat.animals.BabyAnimals {
+ void growUp()
}
class dhbw.ipoat.habitat.BirdHouse {
}
class dhbw.ipoat.transportationdevice.Cart {
- List<Mammal> draughtAnimals
- int sizeOfCart
- int wheelCount
- int animalCount
- boolean home
+ int getAnimalCount()
+ void setHome(boolean)
+ List<Mammal> getDraughtAnimals()
+ boolean isHome()
+ void putAnimalsInFront(List<Mammal>)
}
class dhbw.ipoat.animals.mammals.Horse {
}
class dhbw.ipoat.transportationdevice.Bag {
}
enum dhbw.ipoat.animals.birds.BirdList {
+  PIGEON
}
class dhbw.ipoat.habitat.Habitat {
# List<Bird> birdOlds
# int avaliableNests
# int costOfNewNest
# int maxCapacity
# int relaxingFactor
# int amountOfChargingStations
# int costOfChargingStation
# int dailyCost
- Map<String,Animal> mapNameToBird
# List<Animal> animalsInHabitat
# String nameOfHabitat
# Player player
# String type
# int cost
# HabitatTypes habitatTypes
+ int getCost()
+ HabitatTypes getHabitatTypes()
+ int getDailyCost()
+ String getType()
+ int getMaxCapacity()
+ List<Animal> getAnimalsInHabitat()
+ Map<String,Animal> getMapNameToBird()
+ int getCostOfNewNest()
+ int getAmountOfChargingStations()
+ int getCostOfChargingStation()
+ void setCostOfChargingStation(int)
+ int getRelaxingFactor()
+ void increaseChargingStations()
+ List<Animal> getAnimals()
+ boolean isEnoughSpace()
+ void addAnimalToHabitat(Animal)
+ void IncreaseSizeOfHabitat()
+ String getNameOfHabitat()
+ void decreaseNests(int)
+ int getAvaliableNests()
}
class dhbw.ipoat.employee.Employee {
- {static} int employeeCounter
- {static} int recruitmentFee
- EmployeeNames name
- int dailyCost
- String employeeID
+ {static} int getRecruitmentFee()
+ int getDailyCost()
+ String getEmployeeID()
+ EmployeeNames getName()
}
class dhbw.ipoat.habitat.Stall {
}
class dhbw.ipoat.animals.birds.Bird {
- Bag bag
+ Bag getBag()
+ {static} boolean doesThisAnimalExist(String)
}
class dhbw.ipoat.animals.mammals.Mammal {
- Backpack backpack
# Employee rider
+ Backpack getBackpack()
+ {static} boolean doesThisAnimalExist(String)
}
class dhbw.ipoat.player.Player {
- List<Medium> avaliableMedia
- int day
- String name
- float money
- float amountDataTransmitted
- HashMap<String,TransportDevice> allTransportDevices
- HashMap<String,Habitat> habitatDict
- HashMap<String,TransportDevice> transportDict
- HashMap<String,Medium> mediumDict
- HashMap<String,Computer> computerDict
- HashMap<String,Employee> employeeDict
+ HashMap<String,Employee> getEmployeeDict()
+ HashMap<String,Medium> getMediumDict()
+ HashMap<String,Computer> getComputerDict()
+ HashMap<String,TransportDevice> getTransportDict()
+ String getName()
+ HashMap<String,Habitat> getHabitatDict()
+ HashMap<String,TransportDevice> getAllTransportDevices()
+ float getAmountDataTransmitted()
+ void setAmountDataTransmitted(float)
+ void moneyTransactions(float)
+ List<Medium> getAvaliableMedia()
+ void setAvaliableMedia(List<Medium>)
+ float getMoney()
+ void setMoney(int)
+ void NextDay()
+ int getDay()
+ void setDay(int)
+ boolean checkForDoubleNames(String)
+ void unloadData(float)
+ List<Animal> getAllAnimals()
+ TransportDevice getTransportDeviceWithName(String)
+ void addAnimalToHabitat(Animal)
+ void removeAnimalFromArchives(Animal)
+ Medium getMediumWithName(String)
+ Animal getAnimalWithName(String)
}
class dhbw.ipoat.transportationdevice.TransportDevice {
# List<Medium> mediaInDevice
# int maxObjects
# int cost
# int costForUpgrade
# float weight
# float probabilityOfFailure
# String uuid
# Player player
# String type
+ String getUuid()
+ String getType()
+ int getMaxObjects()
+ void attachDevice(Animal)
+ float calculateWeight()
+ void removeObject(Medium)
+ List<Medium> getMediaInDevice()
+ void load(Player,Animal)
+ void putMedium(Medium)
+ void unloadData()
+ float calculateData()
+ void increaseSize()
# void notifyPlayer(String)
+ TransportDevice getTransportDevice()
}
class dhbw.ipoat.medium.FloppyDisk {
}
class dhbw.ipoat.animals.Animal {
# int age
# int maxAge
# int speed
# int energy
# int cost
# String name
# String type
# boolean home
# boolean delivering
# float maxWeight
# Player player
# float deathProbability
# float percentageMoved
# TransportDevice device
# boolean gender
# int breedingCooldown
# HabitatTypes habitatType
+ boolean isDelivering()
+ HabitatTypes getHabitatType()
+ int getMaxAge()
+ void setBreedingCooldown(int)
+ int getBreedingCooldown()
+ TransportDevice getDevice()
+ int getSpeed()
+ void setDevice(TransportDevice)
+ void agingAnimal()
+ String getName()
+ void killAnimal()
- boolean checkForAttachedTransport()
+ boolean isGender()
+ void moveAnimal()
+ float calculateValueOfAnimal()
+ void setHome(boolean)
+ float getDeathProbability()
+ int getCost()
+ String getTypeOfAnimal()
+ boolean isHome()
+ int getAge()
+ int getEnergy()
+ float getMaxWeight()
+ void setEnergy(int)
}
class dhbw.ipoat.transportationdevice.Backpack {
}
enum dhbw.ipoat.employee.Occupations {
+  NONE
+  RIDING
+  LOADING
}
class dhbw.ipoat.animals.mammals.Elephant {
}
enum dhbw.ipoat.animals.mammals.MammalList {
+  Ox
+  Horse
+  Elephant
}
enum dhbw.ipoat.habitat.HabitatTypes {
+  STALL
+  BIRDHOUSE
}


dhbw.ipoat.animals.Animal <|-- dhbw.ipoat.animals.GrownAnimals
dhbw.ipoat.animals.birds.Bird <|-- dhbw.ipoat.animals.birds.Pigeon
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Ox
dhbw.ipoat.animals.Animal <|-- dhbw.ipoat.animals.BabyAnimals
dhbw.ipoat.habitat.Habitat <|-- dhbw.ipoat.habitat.BirdHouse
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Cart
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Horse
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Bag
dhbw.ipoat.habitat.Habitat <|-- dhbw.ipoat.habitat.Stall
dhbw.ipoat.animals.GrownAnimals <|-- dhbw.ipoat.animals.birds.Bird
dhbw.ipoat.animals.GrownAnimals <|-- dhbw.ipoat.animals.mammals.Mammal
dhbw.ipoat.medium.Medium <|-- dhbw.ipoat.medium.FloppyDisk
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Backpack
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Elephant
@enduml