@startuml
class dhbw.ipoat.commands.CommandSave {
+ void execute(String)
}
enum dhbw.ipoat.commands.CommandToken {
+  PUT
+  BUY
+  UPGRADE
+  NEXT
+  SEND
+  STATS
+  HELP
+  SELL
+  LIST
+  EXIT
+  LOAD
+  INVENTORY
+  REMOVE
+  PUFFER
+  BREED
+  ATTACH
+  RECRUIT
+  SACK
+  SAVE
+  AUTOSAVE
+  SOUND
+  SWITCH
}
enum dhbw.ipoat.employee.EmployeeNames {
+  Janick
+  Timo
+  Andreas
+  Lars
+  Nico
+  Felix
+  David
+  Markus
+  Christin
+  Claudia
+  Laura
+  Katja
+  Sven
+  Lea
+  Nina
}
class dhbw.ipoat.commands.CommandNextDay {
+ void execute(String)
- void letAnimalRest(Animal)
}
class dhbw.ipoat.medium.Medium {
# String nameOfMedium
# float weight
# float cost
# float data
# String id
# boolean full
+ String getNameOfMedium()
+ boolean isFull()
+ void setFull(boolean)
+ float getData()
+ float getCost()
+ String getId()
+ float getWeight()
+ void setWeight(float)
}
abstract class dhbw.ipoat.commands.CommandTemplate {
# {static} Player player
+ {abstract}void execute(String)
+ {static} void setPlayer(Player)
}
abstract class dhbw.ipoat.animals.GrownAnimals {
# int cost
# boolean home
# boolean delivering
# int breedingCooldown
# TransportDevice transport
# AnimalImplementation animalImplementation
+ {abstract}void MakeSound()
+ TransportDevice getTransport()
+ AnimalImplementation getAnimalImplementation()
+ void setAnimalImplementation(AnimalImplementation)
}
class dhbw.ipoat.animals.ConsoleSoundGenerator {
+ void MakeAnimalSound(String)
}
class dhbw.ipoat.commands.CommandPut {
+ void execute(String)
}
class dhbw.ipoat.transportationdevice.TransportDevice {
# List<Medium> mediaInDevice
# int maxObjects
# int cost
# int costForUpgrade
# float weight
# float probabilityOfFailure
# String uuid
# Player player
# String type
+ String getUuid()
+ String getType()
+ int getMaxObjects()
+ void attachDevice(Animal)
+ float calculateWeight()
+ void removeObject(Medium)
+ List<Medium> getMediaInDevice()
+ void load(Player,Animal)
+ void putMedium(Medium)
+ void unloadData()
+ float calculateData()
+ void increaseSize()
# void notifyPlayer(String)
+ TransportDevice getTransportDevice()
}
class dhbw.ipoat.animals.AudioSoundGenerator {
+ void MakeAnimalSound(String)
}
class dhbw.ipoat.commands.CommandSound {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandAutosave {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandRemove {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandExit {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandBreed {
+ void execute(String)
- void resetBreedingCooldown(Animal)
}
enum dhbw.ipoat.animals.birds.BirdList {
+  PIGEON
}
abstract class dhbw.ipoat.savesystem.Savegame {
- {static} List<Player> allPlayers
+ {static} boolean bypassEncryption
+ {static} Boolean autosave
+ {static} void save(Player)
- {static} JSONObject savePlayer(Player)
+ {static} void writeToFile(JSONObject)
}
class dhbw.ipoat.transportationdevice.Backpack {
}
class dhbw.ipoat.commands.CommandUpgrade {
+ void execute(String)
}
class dhbw.ipoat.savesystem.LoadSaveGame {
- {static} String jsonString()
+ {static} Player load()
- {static} Animal getAnimalFromType(String,Player,JSONObject)
- {static} Habitat getHabitatFromType(String,Player,JSONObject)
}
class dhbw.ipoat.computer.Computer {
- float writingSpeed
- float generationSpeed
- List<Medium> mediaInPC
- String nameOfPc
- float puffer
- float maxPuffer
- float cost
- float dataTransmitted
~ Instant pcStartTime
+ void GenerateData()
+ Instant getPcStartTime()
+ float getPuffer()
+ void transferData(Medium)
+ String getNameOfPc()
}
class dhbw.ipoat.commands.CommandMapTest {
}
class dhbw.ipoat.savesystem.SavegameTest {
}
class dhbw.ipoat.commands.CommandMap {
+ GUI gui
- Map<CommandToken,CommandTemplate> commands
- Player player
- Boolean autosave
+ {static} outputPossibilities mode
+ void execute(CommandToken,String)
- void initializeMap()
}
enum dhbw.ipoat.commands.outputPossibilities {
+  CONSOLE
+  SPEAKER
}
class dhbw.ipoat.encrypt.EncryptionTest {
+ void doEncryption()
+ void doEncryptionWithAllCharacters()
+ void doDecrypting()
}
class dhbw.ipoat.commands.CommandPuffer {
+ void execute(String)
}
class dhbw.ipoat.savesystem.JsonConstants {
+ {static} String SAVEGAMEFILE
+ {static} String PLAYERS
+ {static} String NAME
+ {static} String MON
+ {static} String INV
+ {static} String HAB
+ {static} String MED
+ {static} String TRA
+ {static} String DEFAULTSAVEGAME
}
class dhbw.ipoat.habitat.Habitat {
# List<Bird> birdOlds
# int avaliableNests
# int costOfNewNest
# int maxCapacity
# int relaxingFactor
# int amountOfChargingStations
# int costOfChargingStation
# int dailyCost
- Map<String,Animal> mapNameToBird
# List<Animal> animalsInHabitat
# String nameOfHabitat
# Player player
# String type
# int cost
# HabitatTypes habitatTypes
+ int getCost()
+ HabitatTypes getHabitatTypes()
+ int getDailyCost()
+ String getType()
+ int getMaxCapacity()
+ List<Animal> getAnimalsInHabitat()
+ Map<String,Animal> getMapNameToBird()
+ int getCostOfNewNest()
+ int getAmountOfChargingStations()
+ int getCostOfChargingStation()
+ void setCostOfChargingStation(int)
+ int getRelaxingFactor()
+ void increaseChargingStations()
+ List<Animal> getAnimals()
+ boolean isEnoughSpace()
+ void addAnimalToHabitat(Animal)
+ void IncreaseSizeOfHabitat()
+ String getNameOfHabitat()
+ void decreaseNests(int)
+ int getAvaliableNests()
}
class dhbw.ipoat.commands.CommandInventory {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandSwitch {
+ void execute(String)
- void setAllAnimalImplementations()
}
enum dhbw.ipoat.habitat.HabitatTypes {
+  STALL
+  BIRDHOUSE
}
abstract class dhbw.ipoat.animals.birds.Bird {
- Bag bag
+ Bag getBag()
+ {static} boolean doesThisAnimalExist(String)
}
class dhbw.ipoat.computer.ComputerTest {
~ void generateData()
}
class dhbw.ipoat.habitat.BirdHouse {
}
class dhbw.ipoat.habitat.Stall {
}
enum dhbw.ipoat.animals.mammals.MammalList {
+  Ox
+  Horse
+  Elephant
}
class dhbw.ipoat.commands.CommandSellObject {
+ void execute(String)
}
class dhbw.ipoat.animals.BabyAnimal {
+ void growUp()
}
class dhbw.ipoat.commands.CommandSend {
+ void execute(String)
}
class dhbw.ipoat.transportationdevice.Cart {
- List<Mammal> draughtAnimals
- int sizeOfCart
- int wheelCount
- int animalCount
- boolean home
+ int getAnimalCount()
+ void setHome(boolean)
+ List<Mammal> getDraughtAnimals()
+ boolean isHome()
+ void putAnimalsInFront(List<Mammal>)
}
class dhbw.ipoat.player.PlayerTest {
~ void moneyTransactions()
}
interface dhbw.ipoat.commands.GUI {
+ String in()
+ void out(String)
+ void debug(String)
}
class dhbw.ipoat.animals.mammals.Horse {
+ void MakeSound()
}
class dhbw.ipoat.transportationdevice.Bag {
}
class dhbw.ipoat.animals.birds.Pigeon {
+ void MakeSound()
}
class dhbw.ipoat.Main {
~ {static} Player player
+ {static} void main(String[])
}
class dhbw.ipoat.commands.CommandAttatch {
+ void execute(String)
}
class dhbw.ipoat.medium.FloppyDisk {
}
class dhbw.ipoat.commands.CommandHelp {
+ void execute(String)
}
class dhbw.ipoat.player.Player {
- List<Medium> avaliableMedia
- int day
- String name
- float money
- float amountDataTransmitted
- HashMap<String,TransportDevice> allTransportDevices
- HashMap<String,Habitat> habitatDict
- HashMap<String,TransportDevice> transportDict
- HashMap<String,Medium> mediumDict
- HashMap<String,Computer> computerDict
- HashMap<String,Employee> employeeDict
+ HashMap<String,Employee> getEmployeeDict()
+ HashMap<String,Medium> getMediumDict()
+ HashMap<String,Computer> getComputerDict()
+ HashMap<String,TransportDevice> getTransportDict()
+ String getName()
+ HashMap<String,Habitat> getHabitatDict()
+ HashMap<String,TransportDevice> getAllTransportDevices()
+ float getAmountDataTransmitted()
+ void setAmountDataTransmitted(float)
+ void moneyTransactions(float)
+ List<Medium> getAvaliableMedia()
+ void setAvaliableMedia(List<Medium>)
+ float getMoney()
+ void setMoney(float)
+ void NextDay()
+ int getDay()
+ void setDay(int)
+ boolean checkForDoubleNames(String)
+ void unloadData(float)
+ List<Animal> getAllAnimals()
+ TransportDevice getTransportDeviceWithName(String)
+ void addAnimalToHabitat(Animal)
+ void removeAnimalFromArchives(Animal)
+ Medium getMediumWithName(String)
+ Animal getAnimalWithName(String)
}
abstract class dhbw.ipoat.animals.mammals.Mammal {
- Backpack backpack
# Employee rider
+ Backpack getBackpack()
+ {static} boolean doesThisAnimalExist(String)
}
enum dhbw.ipoat.employee.Occupations {
+  NONE
+  RIDING
+  LOADING
}
class dhbw.ipoat.animals.mammals.Ox {
+ void MakeSound()
}
class dhbw.ipoat.Terminal {
- boolean debug
+ String in()
+ void out(String)
+ void debug(String)
}
class dhbw.ipoat.commands.CommandBreedTest {
}
class dhbw.ipoat.animals.Animal {
# int age
# int maxAge
# int speed
# int energy
# int cost
# String name
# String type
# boolean home
# boolean delivering
# float maxWeight
# Player player
# float deathProbability
# float percentageMoved
# TransportDevice device
# boolean gender
# int breedingCooldown
# HabitatTypes habitatType
+ boolean isDelivering()
+ HabitatTypes getHabitatType()
+ int getMaxAge()
+ void setBreedingCooldown(int)
+ int getBreedingCooldown()
+ TransportDevice getDevice()
+ int getSpeed()
+ void setDevice(TransportDevice)
+ void agingAnimal()
+ String getName()
+ void killAnimal()
- boolean checkForAttachedTransport()
+ boolean isGender()
+ void moveAnimal()
+ float calculateValueOfAnimal()
+ void setHome(boolean)
+ float getDeathProbability()
+ int getCost()
+ String getTypeOfAnimal()
+ boolean isHome()
+ int getAge()
+ int getEnergy()
+ float getMaxWeight()
+ void setEnergy(int)
}
class dhbw.ipoat.commands.CommandRecruit {
+ void execute(String)
}
class dhbw.ipoat.events.Event {
+ void doSomethingGoodOrBad(int,Player)
}
interface dhbw.ipoat.animals.AnimalImplementation {
~ void MakeAnimalSound(String)
}
class dhbw.ipoat.commands.CommandStats {
+ void execute(String)
}
class dhbw.ipoat.employee.Employee {
- {static} int employeeCounter
- {static} int recruitmentFee
- EmployeeNames name
- int dailyCost
- String employeeID
+ {static} int getRecruitmentFee()
+ int getDailyCost()
+ String getEmployeeID()
+ EmployeeNames getName()
}
class dhbw.ipoat.habitat.HabitatTest {
~ void increaseSizeOfHabitat()
}
class dhbw.ipoat.commands.CommandBuy {
+ void execute(String)
- void determineHabitat(Animal)
- void addAnimal(Habitat,Animal)
- void addMediumToPlayer(Medium)
}
class dhbw.ipoat.animals.mammals.Elephant {
+ void MakeSound()
}
class dhbw.ipoat.commands.CommandSack {
+ void execute(String)
}
abstract class dhbw.ipoat.encrypt.Encryption {
- {static} int[][] encryptingArray
- {static} int chunkSize
- {static} int seedLength
- {static} void setupEncryptingArray()
+ {static} String doEncryption(String,int)
+ {static} String doDecrypting(String)
- {static} char decryptCharacter(String)
- {static} String generateSeed(int)
- {static} void swapAxis(boolean,String)
}
class dhbw.ipoat.commands.CommandList {
+ void execute(String)
}
class dhbw.ipoat.commands.CommandLoad {
+ void execute(String)
}


dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSave
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandNextDay
dhbw.ipoat.animals.Animal <|-- dhbw.ipoat.animals.GrownAnimals
dhbw.ipoat.animals.AnimalImplementation <|.. dhbw.ipoat.animals.ConsoleSoundGenerator
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandPut
dhbw.ipoat.animals.AnimalImplementation <|.. dhbw.ipoat.animals.AudioSoundGenerator
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSound
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandAutosave
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandRemove
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandExit
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandBreed
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Backpack
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandUpgrade
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandPuffer
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandInventory
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSwitch
dhbw.ipoat.animals.GrownAnimals <|-- dhbw.ipoat.animals.birds.Bird
dhbw.ipoat.habitat.Habitat <|-- dhbw.ipoat.habitat.BirdHouse
dhbw.ipoat.habitat.Habitat <|-- dhbw.ipoat.habitat.Stall
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSellObject
dhbw.ipoat.animals.Animal <|-- dhbw.ipoat.animals.BabyAnimal
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSend
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Cart
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Horse
dhbw.ipoat.transportationdevice.TransportDevice <|-- dhbw.ipoat.transportationdevice.Bag
dhbw.ipoat.animals.birds.Bird <|-- dhbw.ipoat.animals.birds.Pigeon
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandAttatch
dhbw.ipoat.medium.Medium <|-- dhbw.ipoat.medium.FloppyDisk
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandHelp
dhbw.ipoat.animals.GrownAnimals <|-- dhbw.ipoat.animals.mammals.Mammal
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Ox
dhbw.ipoat.commands.GUI <|.. dhbw.ipoat.Terminal
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandRecruit
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandStats
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandBuy
dhbw.ipoat.animals.mammals.Mammal <|-- dhbw.ipoat.animals.mammals.Elephant
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandSack
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandList
dhbw.ipoat.commands.CommandTemplate <|-- dhbw.ipoat.commands.CommandLoad
@enduml